required = [
  "github.com/c3systems/c3-go"
]

ignored = [
  "github.com/c3systems/c3/"
]

[[constraint]]
  name = "github.com/c3systems/c3-go"
  branch = "develop"

[[constraint]]
  name = "github.com/c3systems/c3-sdk-go"
  branch = "develop"
