required = [
  "github.com/c3systems/c3-go",
  "github.com/ipfs/go-verifcid"
]

ignored = [
  "github.com/c3systems/c3/"
]

[[override]]
  name =  "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/c3systems/c3-go"
  branch = "develop"

[[constraint]]
  name = "github.com/c3systems/c3-sdk-go"
  branch = "develop"

[[constraint]]
  name = "github.com/ipfs/go-verifcid"
  branch = "master"
